name: Prepare Image Tag
description: Converts PascalCase to snake_case and adds PR suffix
inputs:
  input:
    description: The PascalCase input string
    required: true
outputs:
  value:
    description: The converted image tag
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        INPUT="${{ inputs.input }}"

        # Convert PascalCase to snake_case
        SNAKE_CASE=$(echo "$INPUT" | sed -r 's/([A-Z])/_\L\1/g' | sed 's/^_//')

        # Check if this is a PR
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
          SNAKE_CASE="${SNAKE_CASE}_pr_${PR_NUMBER}"
        fi

        echo "value=$SNAKE_CASE" >> "$GITHUB_OUTPUT"
